var footer = document.getElementsByTagName("footer")[0];
var text = document.createElement("p");
text.innerHTML = "© Hugo Pernin 2025<br>Tous droits réservés.";
footer.appendChild(text);
var link = document.createElement("a");
link.href = "https://www.linkedin.com/in/hugo-pernin/";
link.target = "_blank";
var image = document.createElement("img");
image.src = "img/linkedin.png";
image.alt = "LinkedIn";
image.title = "LinkedIn";
link.appendChild(image);
footer.appendChild(link);
