document.addEventListener("DOMContentLoaded", function () {
    var footer = document.getElementsByTagName("footer")[0];
    footer.classList.remove("pending-footer");
    var text = document.createElement("p");
    text.innerHTML = "© Hugo Pernin 2025<br>Tous droits réservés.";
    footer.appendChild(text);
    var links = document.createElement("div");
    links.id = "footer-links";
    footer.appendChild(links);
    var github = document.createElement("a");
    github.href = "https://github.com/Hugo-Pernin";
    github.target = "_blank";
    links.appendChild(github);
    var githubImage = document.createElement("img");
    githubImage.src = "img/github.svg";
    githubImage.alt = "GitHub";
    githubImage.title = "GitHub";
    github.appendChild(githubImage);
    var linkedin = document.createElement("a");
    linkedin.href = "https://www.linkedin.com/in/hugo-pernin/";
    linkedin.target = "_blank";
    links.appendChild(linkedin);
    var linkedinImage = document.createElement("img");
    linkedinImage.src = "img/linkedin.png";
    linkedinImage.alt = "LinkedIn";
    linkedinImage.title = "LinkedIn";
    linkedin.appendChild(linkedinImage);
});
